### ISSUE TITLE
Turbo is still caching the chart - even when setting `turbo-cache-control` to `no-cache`

### ISSUE THREAD

**Issue by tamersalama** [railsjazz/rails_charts#12]
I believe I've done everything possible to disable cache on the page where the chart renders, however, chart values are still 'sticky'. I get chart rendered for unintended values.

**Comment by igorkasyanchuk** [comment]
@tamersalama as before please try to fork and fix yourself. Maybe even creating a dummy app with this issue can be helpful, so anyone can reproduce the issue.

**Comment by manastyretskyi** [comment]
Yes, having at least dummy app where this reproduces would be helpful

**Comment by manastyretskyi** [comment]
Going to close this issue for now. Feel free to add new comments or open new issue if the problem is still present.
