### ISSUE TITLE
radar chart data format

### ISSUE THREAD

**Issue by xiaozhanzi** [railsjazz/rails_charts#18]
I am trying to create a radar chart with rails_charts, but couldn't figure out the data format. Could you please provide a sample for generating a radar chart?

**Comment by igorkasyanchuk** [comment]
See in the dummy app + readme

https://github.com/railsjazz/rails_charts/blob/b424bd1eb0a047080afb66a939ae6279f49bb82c/test/dummy/app/models/user.rb#L17
