### ISSUE TITLE
Missing Charts. 

### ISSUE THREAD

**Issue by Mohamed-Zkaria** [railsjazz/rails_charts#23]
Hi, I want to use map chart and multiple bars chart. They are available in the apache js version but not in rails. Is there a way to use them?

**Comment by igorkasyanchuk** [comment]
Hi, I think bar chart will work (just pass an array with data) https://github.com/railsjazz/rails_charts?tab=readme-ov-file#bar-chart

as for the map (if you referring to https://echarts.apache.org/examples/en/index.html#chart-type-map) - you probably can initialize it with https://github.com/railsjazz/rails_charts?tab=readme-ov-file#custom-chart

**Comment by Mohamed-Zkaria** [comment]
Do I pass the data the same way it's documented in apache docs?

**Comment by igorkasyanchuk** [comment]
like here

https://github.com/railsjazz/rails_charts/blob/main/test/dummy/app/views/home/_custom_chart.html.erb

**Comment by Mohamed-Zkaria** [comment]
ok thank you.

**Comment by Mohamed-Zkaria** [comment]
Hi, I tried the custom chart but it didn't work, I want to render something like this map:
https://echarts.apache.org/examples/en/editor.html?c=map-usa-projection

It seems that it takes two data inputs one for the rendering the map and the other for displaying the values, is there a way to use that? 
Also the double bar chart didn't work passing an array. any documentations for this please?

**Comment by igorkasyanchuk** [comment]
@Mohamed-Zkaria the best will be if you can try to contribute to the gem. Maybe you can add a new map type similar to other types
