### ISSUE TITLE
Stacked line Chart

### ISSUE THREAD

**Issue by hooopo** [railsjazz/rails_charts#9]
Does it support Stacked line Chart? Is there example for doing that?

**Comment by manastyretskyi** [comment]
It looks like stacked option might not be available via `line_chart` helper right now, but you can always build any type of chart you want using `custom_chart` helper
Example of a stacked line chart would be something like this:
```ruby
  <%= custom_chart({
        xAxis: {
          data: ['A', 'B', 'C', 'D', 'E']
        },
        yAxis: {},
        series: [
          {
            data: [10, 22, 28, 43, 49],
            type: 'line',
            stack: 'x'
          },
          {
            data: [5, 4, 3, 5, 10],
            type: 'line',
            stack: 'x'
          }
        ]
      })
  %>
```

**Comment by hooopo** [comment]
thank you,I'll try it👍
